name: Platform IO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - example: get_info
          board: huzzah
        - example: get_info
          board: esp-wrover-kit

    runs-on: ubuntu-latest
    name: Build ${{ matrix.example }}-${{ matrix.board }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install Platform IO
        run:
          |
          pip install -U platformio
          platformio update

      - name: Install Checked out ArduinoMongoose
        run:
          pio lib -g install $GITHUB_WORKSPACE

      - name: Build example 
        run:
          |
          cd examples/${{ matrix.example }}
          pio run -e ${{ matrix.board }}
